### ISSUE TITLE
Gamut Mapping Playground (multiple errors)

### ISSUE THREAD

**Issue by svgeesus** [color-js/apps#8]
The gamut mapping playground has a bunch of console errors (about vue, and undefined objects).
https://apps.colorjs.io/gamut-mapping/

It still seems to work in Firefox, but is totally broken in Chrome.

**Comment by svgeesus** [comment]
Chrome Canary 132:
![image](https://github.com/user-attachments/assets/ada94e5d-c998-4afb-af75-3d7b984cc3fb)

Firefox Nightly 133:
![image](https://github.com/user-attachments/assets/9b2e35a3-c95c-49a9-8e26-537c630795e7)

**Comment by DmitrySharabin** [comment]
Fixed in https://github.com/color-js/apps/pull/10
